version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - ml
    environment:
      - ML_API_URL=http://ml:8000

  ml:
    build: ./ml_service
    ports:
      - "8000:8000"
